sudo: required

language: cpp

before_install:
  - apt -y -qq update
  - apt -y -qq full-upgrade
  - apt -y -qq install git gcc-10 g++-10 cmake libboost-dev libasound-dev libjack-dev ninja-build

script:
  - mkdir build
  - cd build
  - cmake -G Ninja ..
  - cmake --build .

